meta_product_name: "Charlie"
meta_title: "Charlie - A Breath of Fresh Air in your Palm"
meta_description: "Charlie helps you soothe panic attacks with a simple breathing exercise. Whenever you need someone to calm you down, Charlie is there for you. "
#meta_image: "cover.png" # should exist in `app/assets/images/`
#twitter_account: "@product_twitter_account"   # required for Twitter Cards